# Task 1: Tensor Quantization and Dequantization 

File: task_01_basic_quantization.ipynb 

# Objective 

Implement basic affine INT8 quantization and dequantization using NumPy. Scale and zero points are given so you can focus purely on the quantization and dequantization formulas. 

## Formulas 

Quantization:    q = round(x / scale) + zero_point 

Dequantization:  x_dequantized = (q - zero_point) * scale 

Clip range:     [-128, 127] 

## Input 

tensor = np.array([1.0, -0.5, 3.2, -2.8, 0.0], dtype=np.float32) 

scale = 0.025 

zero_point = 0 

# Implementation 

def quantize_tensor(tensor, scale, zero_point): 

    # Divide by scale, round, add zero-point, clip to [-128, 127] 

    # Return as np.int8 

    pass 

 

def dequantize_tensor(quantized_tensor, scale, zero_point): 

    # Subtract zero point, multiply by scale 

    # Return as float 

    pass 

# Expected Output 

Print all the following: 

Original tensor:              [1.0, -0.5, 3.2, -2.8, 0.0] 

Quantized tensor (INT8):      [?, ?, ?, ?, ?] 

Dequantized tensor (float):   [?, ?, ?, ?, ?] 

Absolute error per element:   [?, ?, ?, ?, ?] 

Mean Absolute Error (MAE):    ? 

Maximum Absolute Error:       ? 

# Deliverable 

A completed notebook showing the original tensor, quantized tensor, dequantized tensor, and all error metrics printed clearly. 

In [3]:
import torch

In [4]:
# Input tensor
tensor = torch.tensor([1.0, -0.5, 3.2, -2.8, 0.0], dtype=torch.float32)

scale = 0.025
zero_point = 0

In [5]:
def quantize_tensor(tensor, scale, zero_point):
    """
    Quantize a float tensor to INT8 .
    """
    q = torch.round(tensor / scale) + zero_point
    q = torch.clamp(q, -128, 127)
    return q.to(torch.int8)


def dequantize_tensor(quantized_tensor, scale, zero_point):
    """
    Dequantize an INT8 tensor back to float
    """
    return (quantized_tensor.to(torch.float32) - zero_point) * scale

In [6]:
# Quantize
quantized_tensor = quantize_tensor(tensor, scale, zero_point)

# Dequantize
dequantized_tensor = dequantize_tensor(quantized_tensor, scale, zero_point)

# Error metrics
absolute_error = torch.abs(tensor - dequantized_tensor)
mae = torch.mean(absolute_error)
max_error = torch.max(absolute_error)

In [7]:
print("Original tensor:")
print(tensor)

print("\nQuantized tensor (INT8):")
print(quantized_tensor)

print("\nDequantized tensor (float):")
print(dequantized_tensor)

print("\nAbsolute error per element:")
print(absolute_error)

print("\nMean Absolute Error (MAE):")
print(mae.item())

print("\nMaximum Absolute Error:")
print(max_error.item())

Original tensor:
tensor([ 1.0000, -0.5000,  3.2000, -2.8000,  0.0000])

Quantized tensor (INT8):
tensor([  40,  -20,  127, -112,    0], dtype=torch.int8)

Dequantized tensor (float):
tensor([ 1.0000, -0.5000,  3.1750, -2.8000,  0.0000])

Absolute error per element:
tensor([0.0000, 0.0000, 0.0250, 0.0000, 0.0000])

Mean Absolute Error (MAE):
0.005000018980354071

Maximum Absolute Error:
0.02500009536743164
